---
namespace: nginxinc
name: nginx_core
description: Install and configure NGINX and NGINX App Protect using Ansible
version: 0.3.0
readme: README.md
license_file: LICENSE
authors:
  - Alessandro Fael Garcia <a.faelgarcia@f5.com>
dependencies: {}

tags:
  - nginx
  - nginx_plus
  - nginx_config
  - nginx_app_protect
  - oss
  - opensource
  - plus
  - web
  - server
  - development
  - install
  - configuration
  - waf
  - security

repository: https://github.com/nginxinc/ansible-collection-nginx
homepage: https://github.com/nginxinc/ansible-collection-nginx
documentation: https://github.com/nginxinc/ansible-collection-nginx/blob/main/README.md
issues: https://github.com/nginxinc/ansible-collection-nginx/issues
